### ISSUE TITLE
Adding class files to project dependencies

### ISSUE THREAD

**Issue by bryan4887** [vontikov/sbe-gradle-plugin#5]
Hello, thanks for the useful plugin. Would you mind showing us how to add the Java codecs .class files to the classpath? Either that or showing how to make the JAR a dependency of the project would be super useful. 

The plugin is successfully providing the new gradle tasks, but I don't know how to then link everything together. 

Thanks in advance!

**Comment by vontikov** [comment]
Hi Bryan,

I will provide an example in a couple of days.

Regards,
Vladimir

пт, 15 мая 2020 г., 18:25 Bryan Hernandez <notifications@github.com>:

**Comment by bryan4887** [comment]
Fantastic! Thank you, Vladmir!

**Comment by vontikov** [comment]
Hi Bryan,

I've provided the example <https://github.com/vontikov/sbe-example>you
asked me about. In this example program code and generated codecs share the
same source tree, compiled classes share the same jar,
*and sbeGenerateJavaCodecs is *the only plugin task you need to execute
each time you've changed the XML schema.

Another way of using the plugin is placing compiled codecs into a separate
jars - *sbeJavaArchive* task. By default the jar, containing compiled
codecs, will be copied into build/archives folder.
Then the jar may be shared between different projects, usually via an
artifactory.

Regards,
Vladimir Ontikov







сб, 16 мая 2020 г. в 17:53, Bryan Hernandez <notifications@github.com>:
