### ISSUE TITLE
Only first java option is passed to SBE Tool

### ISSUE THREAD

**Issue by eduard-batmendijn-SF** [vontikov/sbe-gradle-plugin#7]
When I specify multiple options for SBE Tool, e.g.

```kotlin
sbeGenerator {
    javaOptions = mapOf(
        "sbe.xinclude.aware" to true,
        "sbe.types.package.override" to true,
    )
}
```

only the first option is passed to SBE Tool.

I have no experience in Groovy, but the bug seems to be here:
https://github.com/vontikov/sbe-gradle-plugin/blob/2568bd37cc265c4c29abaac01024b17e31b7028f/src/main/groovy/com/github/vontikov/SbeGeneratorPlugin.groovy#L95

I believe `Map.every` returns after first option's predicate evaluates to false. I think `Map.each` would be more suitable here.

**Comment by vontikov** [comment]
@eduard-batmendijn-SF, thanks!
